### ISSUE TITLE
Missing source 

### ISSUE THREAD

**Issue by ghost** [abs-tudelft/arrow-gen#1]
Hi thanks for this looks really interesting.

Did you actually refactor BWA to work with arrow? If so, then any chance I can look at the source? 

Were other tools refactored to work with arrow as well? I’m interested in moving my tool chain to use plasma + arrow.

**Comment by tahashmi** [comment]
Hi, thanks! 
Yes, I have just changed BWA-MEM to put data in in-memory Arrow format instead of writing into SAM I/O file. Then stored it in Plasma objects so that other tools like Picard and GATK can manipulate that data. Picard and GATK also modified to interpret Plasma objects and Arrow format instead of SAM files.

**Comment by ghost** [comment]
Awesome. Any chance I can see the source for all of this? I’m wanting to do the same for some of my tools.

**Comment by tahashmi** [comment]
Yes, Sure. I have added some description in the README file. The code is yet not cleaned. But you can get an idea.  https://github.com/tahashmi/bwa/blob/master/README.md

**Comment by jamesthegiantpeach** [comment]
Ok awesome! Same performance as usual bwa?

**Comment by ghost** [comment]
Hi again, by any chance do you still have the htsjdk source?

**Comment by tahashmi** [comment]
Here's the [link](https://drive.google.com/file/d/1HoJbkjhC8e5ltwhfDHnp0rP1TPXpmJV1/view?usp=sharing).
